version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pulse
      MYSQL_USER: pulse
      MYSQL_PASSWORD: pulse
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: pulse-services
    restart: always
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/pulse?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: pulse
      SPRING_DATASOURCE_PASSWORD: pulse
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data: